### ISSUE TITLE
Access errors

### ISSUE THREAD

**Issue by Firesphere** [SilbinaryWolf/silverstripe-steamedclams#16]
All files are rejected, due to access errors
Even though, none of these files are actually infected

198.41.238.115 | 7 (Edit) | /var/www/public/assets/Uploads/myimage.jpg | admin/queuedjobs/Symbiote-QueuedJobs-DataObjects-QueuedJobDescriptor/EditForm/field/QueuedJobDescriptor | Deleted, File was infected | Access denied. ERROR
-- | -- | --
198.41.238.115 | 7 (Edit) | /var/www/public/assets/Uploads/myimage.jpg | admin/queuedjobs/Symbiote-QueuedJobs-DataObjects-QueuedJobDescriptor/EditForm/field/QueuedJobDescriptor | Infected, Pending Action | Can't open file or directory ERROR

**Comment by nglasl** [comment]
I'd be curious to know if anyone else is having this issue too? I know we're using this module across a few projects without problems. I assume you've checked your folder permissions.

**Comment by Firesphere** [comment]
I can see the problem, after looking at it a bit closer.

The path is `/var/www/public`. This is incorrect, it needs to be `/var/www/{$domain}/web/public`

Seems the path is detected wrong in the scan?
