### ISSUE TITLE
Add/create reports

### ISSUE THREAD

**Issue by Firesphere** [SilbinaryWolf/silverstripe-steamedclams#5]
A report showing the amount of files detected/scanned/unscanned per day etc. would be nice

**Comment by silbinarywolf** [comment]
A report in what way?
Like an email out? An SS_Report?

I agree it would be very handy, just haven't given the implementation too much thought yet.

**Comment by Firesphere** [comment]
Yeah, an SS_Report indeed. Would add a lot of value (from customer experience and their love for getting extensive reports)

**Comment by Firesphere** [comment]
Fixed in PR #10
