### ISSUE TITLE
QueuedJobs

### ISSUE THREAD

**Issue by Firesphere** [SilbinaryWolf/silverstripe-steamedclams#8]
Isn't QueuedJobs a requirement? I would guess a build would fail if it wasn't there?

**Comment by silbinarywolf** [comment]
It shouldn't fail. I have a class_exists() check wrapping around it.
QueuedJobs should probably be a suggestion in the composer.json however.

**Comment by Firesphere** [comment]
Excellent solution :)

**Comment by silbinarywolf** [comment]
Updated composer.json with suggestion.
